Liqwid-Labs/liqwid-plutarch-extra

liqwid-plutarch-extra.cabal, src/Plutarch/Extra/FixedDecimal.hs
=> `PFixedDecimal`

flake.nix, src/Plutarch/Api/V1/ScriptContext.hs
more functions for making addresses
=> add address utils, add entr to flake (for 'make watch')

liqwid-plutarch-extra.cabal, src/Plutarch/Extra/Traversable.hs, test/Spec.hs, test/Spec/Extra/Traversable.hs
@jeffhappily 
It's not tested yet
=> Use `pfix` for certain `ptraverse` instances

src/Plutarch/Extra/Functor.hs, src/Plutarch/Extra/IsData.hs, src/Plutarch/Extra/Other.hs, src/Plutarch/Extra/Record.hs, src/Plutarch/Extra/TermCont.hs
=> `PType` to `S -> Type`

src/Plutarch/Extra/Applicative.hs, src/Plutarch/Extra/Category.hs, src/Plutarch/Extra/Functor.hs
Started as applicative, branched into category and functor.
=> add infix declarations

CHANGELOG.md, src/Plutarch/Extra/IsData.hs
This reverts commit 9b8a4b55fdf29512888ca128f81f97a387ccb1f4.
=> Revert "add `DerivePDataFieldsViaDataList`"

CHANGELOG.md, src/Plutarch/Extra/Maybe.hs
See [CHANGLOG](https://github.com/Liqwid-Labs/liqwid-plutarch-extra/blob/3a534725bd63a596cb4fd475f8f0f0a0f16c7a57/CHANGELOG.md) for details.
=> Add a new `pmaybe` function and serveral other utils for `PMaybe`

CHANGELOG.md, hie.yaml, liqwid-plutarch-extra.cabal, src/Plutarch/Extra/Function.hs, src/Plutarch/Extra/ScriptContext.hs, src/Plutarch/Extra/Tuple.hs, src/Plutarch/Orphans.hs
=> Upstream some utils from Agora

flake.lock, flake.nix
=> Point flakes at main branches of PCB and PQ

CHANGELOG.md, liqwid-plutarch-extra.cabal, src/Plutarch/Extra/Time.hs
=> Add `Plutarch.Extra.Time`

.gitignore, CHANGELOG.md, bench/sorting/Main.hs, liqwid-plutarch-extra.cabal, src/Plutarch/Extra/Applicative.hs, src/Plutarch/Extra/AssetClass.hs, src/Plutarch/Extra/Bind.hs, src/Plutarch/Extra/Compile.hs, src/Plutarch/Extra/DebuggableScript.hs, src/Plutarch/Extra/Field.hs, src/Plutarch/Extra/FixedDecimal.hs, src/Plutarch/Extra/Functor.hs, src/Plutarch/Extra/IsData.hs, src/Plutarch/Extra/MultiSig.hs, src/Plutarch/Extra/Ord.hs, src/Plutarch/Extra/Precompile.hs, src/Plutarch/Extra/Record.hs, src/Plutarch/Extra/ScriptContext.hs, src/Plutarch/Extra/Tagged.hs, src/Plutarch/Extra/TermCont.hs, src/Plutarch/Extra/These.hs, src/Plutarch/Extra/Time.hs, src/Plutarch/Extra/Traversable.hs, src/Plutarch/Extra/Tuple.hs, src/Plutarch/Extra/Value.hs, src/Plutarch/Orphans.hs, test/old/Spec/Extra/Map.hs, test/old/Spec/Extra/MultiSig.hs, test/old/Spec/Utils.hs
This brings us into compliance with the new standards for records.
=> Record standards

CHANGELOG.md, liqwid-plutarch-extra.cabal, src/Plutarch/Extra/AssetClass.hs, src/Plutarch/Extra/Value.hs
Reverts Liqwid-Labs/liqwid-plutarch-extra#93 (merged prematurely)
=> Revert "Data AssetClass"

CHANGELOG.md, liqwid-plutarch-extra.cabal, src/Plutarch/Extra/StateThread.hs
This upstreams a generic state thread implementation. I'm not sure if the error messages or naming are optimal though.
=> Initial state thread

CHANGELOG.md, liqwid-plutarch-extra.cabal, src/Plutarch/Extra/Numeric.hs, src/Plutarch/Extra/Rational.hs, test/properties/Main.hs
=> Added integer power to Numeric, along with property test

CHANGELOG.md, liqwid-plutarch-extra.cabal, src/Plutarch/Extra/AssetClass.hs, src/Plutarch/Extra/ExtendedAssetClass.hs
=> ExtendedAssetClass

CHANGELOG.md, liqwid-plutarch-extra.cabal, src/Plutarch/Extra/ExtendedAssetClass.hs
This adds a parallel to `passetClassValueOf'` for `ExtendedAssetClass`.
=> pextendedAssetClassValueOf'

CHANGELOG.md, liqwid-plutarch-extra.cabal, src/Plutarch/Extra/FixedDecimal.hs
Reverts Liqwid-Labs/liqwid-plutarch-extra#131
=> Revert "Fix Data representation for FixedDecimal"

CHANGELOG.md, liqwid-plutarch-extra.cabal, src/Plutarch/Extra/FixedDecimal.hs, src/Plutarch/Orphans.hs
=> Additional Aeson instances

CHANGELOG.md, liqwid-plutarch-extra.cabal, src/Plutarch/Extra/StateThread.hs
Fixes a bug noted by @chfanghr [here](https://github.com/Liqwid-Labs/agora-pro/pull/23#discussion_r1037768988)
=> Fix bug in state token

CHANGELOG.md, liqwid-plutarch-extra.cabal, src/Plutarch/Orphans.hs
My previous versions were very wrong, sorry.
Tested in branch `cjay/json-fixes-working` (without liqwid-nix 2). Not tested in this branch here, because my nix doesn't seem to terminate (without doing any significant CPU load).
=> JSON fixes, actually
