Liqwid-Labs/liqwid-plutarch-extra

- Makefile
- flake.lock
- flake.nix
- liqwid-plutarch-extra.cabal
- src/Plutarch/Api/V1/ScriptContext.hs
- src/Plutarch/Api/V1/Value.hs
- src/Plutarch/Api/V1/Value/Unsorted.hs
- src/Plutarch/Extra/List.hs
- src/Plutarch/Extra/Map.hs
- src/Plutarch/Extra/Map/Sorted.hs
- src/Plutarch/Extra/Map/Unsorted.hs
- src/Plutarch/Extra/Maybe.hs
- src/Plutarch/Extra/TermCont.hs
- test/Spec.hs
- test/Spec/Api/V1/Value.hs
- test/Spec/Api/V1/Value/Unsorted.hs
- test/Spec/Extra/List.hs
- test/Spec/Extra/Map.hs
- test/Spec/Extra/Map/Sorted.hs
- test/Spec/Extra/Map/Unsorted.hs
- test/Spec/Utils.hs
Will close #6.
Here is the manifest:
* `Plutarch.Extra.Map`
* `Plutarch.Extra.Map.Sorted`
* `Plutarch.Extra.Map.Unsorted`
* `Plutarch.Api.V1.Value`
* `Plutarch.Api.V1.Value.Unsorted`
Some other TODOs
> Upstream some utils from Agora

- CHANGELOG.md
- src/Plutarch/Extra/Maybe.hs
- src/Plutarch/Extra/TermCont.hs
Summary: Updated CHANGELOG.md with the new 1.1.0 release and added `pguardWithC` function for some more aggressive traces.
I suppose if we want to create proper releases we really ought to use a `staging`.
> Add release changelog and 'pguardWithC' function

- .gitignore
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/IsData.hs
- `ProductIsData` & the corresponding `PConstantViaDataList` for deriving ToData/FromData/PLift/PConstant/PIsData for record types using the List constructor
- `EnumIsData` & the corresponding `PEnumData` for deriving ToData/FromData/PLift/PConstant/PIsData for Enum types using the PInteger constructor
- `pmatchEnum` & `pmatchEnumFromData` helpers for enums
> Added Extra.IsData module 

- src/Plutarch/Extra/IsData.hs
It turns out that plutarch's default implementation just suits our needs:
```hs
-- ...
default pfromDataImpl :: PIsData (PInner a) => Term s (PAsData a) -> Term s a
pfromDataImpl x = punsafeDowncast $ pfromDataImpl (punsafeCoerce x :: Term _ (PAsData (PInner a)))
-- ...
default pdataImpl :: PIsData (PInner a) => Term s a -> Term s PData
pdataImpl x = pdataImpl $ pto x
```
> Remove redundant custom `IsData` instance

- CHANGELOG.md
- STANDARDS.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/Applicative.hs
- src/Plutarch/Extra/AssetClass.hs
- src/Plutarch/Extra/Const.hs
- src/Plutarch/Extra/DebuggableScript.hs
- src/Plutarch/Extra/Field.hs
- src/Plutarch/Extra/FixedDecimal.hs
- src/Plutarch/Extra/Functor.hs
- src/Plutarch/Extra/Identity.hs
- src/Plutarch/Extra/IsData.hs
- src/Plutarch/Extra/List.hs
- src/Plutarch/Extra/Monoid.hs
- src/Plutarch/Extra/MultiSig.hs
- src/Plutarch/Extra/Profunctor.hs
- src/Plutarch/Extra/Record.hs
- src/Plutarch/Extra/Star.hs
- src/Plutarch/Extra/State.hs
- src/Plutarch/Extra/Sum.hs
- src/Plutarch/Extra/Tagged.hs
- src/Plutarch/Extra/TermCont.hs
- src/Plutarch/Extra/These.hs
- src/Plutarch/Extra/Value.hs
- src/Plutarch/Orphans.hs
This eliminates (most) uses of `generics-sop`. In light of this, we also vendor a version of `Top` (named `Plut`). This also allows us to generalize `.=` to not need `SListI` anymore.
One module `Plutus.Extra.IsData` still uses SOP generics in a fundamental way. As replacing this would be significant, this PR does not address this issue.
Furthermore, in light of the upstream Plutarch changes, we now globally enable `DeriveAnyClass`, `DeriveGeneric` and `TypeFamilies`; the standards document has been updated with this in mind.
> Define Plut, replace uses of Top

- hie.yaml
- src/Plutarch/Extra/Precompile.hs
This was very painful to write. Would be a lot less complicated without using the official `plift'`, but the fallback in case of successfull evaluation followed by a `LiftError` wasn't in the original implementation.
> pliftCompiled: Fallback on LiftErrors, trace messages

- src/Plutarch/Extra/IsData.hs
This will make `PlutusTypeDataList` not complain about the difference between, for example, `PBuiltinList (PAsData PInteger)` and `PBuiltinList PInteger`.
It's helpful because `PTryFrom` only works with former.
> `PlutusTypeDataList` ignores `PAsData`

- src/Plutarch/Extra/DebuggableScript.hs
- src/Plutarch/Extra/MultiSig.hs
Per the recent standards change, all the labelled optics have been rewritten into the inference-friendly (and newline-friendly) forms. I haven't mentioned this or bumped the version, as this is invisible from the point of view of compilation: nothing that used to compile will fail to do so, and in fact, the types are the same exactly, barring some special pleading with GHC.
> Apply simple labelled optics

- CHANGELOG.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/Optics.hs
This upstreams a utility type family for working with labelled-optics-driven records from `liqwid-onchain`.
> HasLabelledGetters

- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/Applicative.hs
- src/Plutarch/Extra/AssetClass.hs
- src/Plutarch/Extra/Bind.hs
- src/Plutarch/Extra/Const.hs
- src/Plutarch/Extra/DebuggableScript.hs
- src/Plutarch/Extra/FixedDecimal.hs
- src/Plutarch/Extra/Identity.hs
- src/Plutarch/Extra/IsData.hs
- src/Plutarch/Extra/Monoid.hs
- src/Plutarch/Extra/MultiSig.hs
- src/Plutarch/Extra/Star.hs
- src/Plutarch/Extra/State.hs
- src/Plutarch/Extra/Sum.hs
- src/Plutarch/Extra/Tagged.hs
- src/Plutarch/Extra/These.hs
- src/Plutarch/Orphans.hs
Since we now require `DuplicateRecordFields` and `UndecidableInstances` to be on everywhere, this PR sets them to be always-on, and removes any case of them being on per-module.
> Compliance with new standards

- CHANGELOG.md
- flake.lock
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/AssetClass.hs
This adds a modifier newtype, similar to `GenCurrencySymbol`, for QuickCheck support for `AssetClass`. It allows control over whether you want the ADA asset class to be generatable or not.
> QuickCheck support for AssetClass

- CHANGELOG.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/FixedDecimal.hs
Forgot something. Also, most `pconstant` are back in, because type inference made the 10 a `Term`, so the `^` would create Plutarch-level calculations.
> FixedDecimal: Zero-cost conversions and optimization

- CHANGELOG.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/ScriptContext.hs
This aims to correct either improper use, or lack of use, of the `try` prefix on Plutarch functions to indicate partiality. I believe this gets them all.
> Resolve improper use of try prefix

- CHANGELOG.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/Optics.hs
This saves typing time by providing a (highly polymorphic) helper `inspect`, which combines `view` and `asks`. Also provided is `inspects`, which parallels `views`.
> inspect and inspects

- CHANGELOG.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/ExtendedAssetClass.hs
These allow easier conversions to a regular `PAssetClass`, as well as `PAssetClassData`, for compatibility with existing functions.
> Conversion utilities for PExtendedAssetClass

- CHANGELOG.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/ExtendedAssetClass.hs
This gives us instances of `PlyArg` and `PlyArgOf` for compatibility with script exports.
> Ply instances for ExtendedAssetClass

- CHANGELOG.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/ExtendedAssetClass.hs
As pointed out by @t1lde, `ptoAssetClass` and `ptoAssetClassData` are inherently unsafe. They have been renamed to `punsafeToAssetClass` and `punsafeToAssetClassData` respectively, and an explanation has been added as to why they're not safe.
> Rename conversions to mark them unsafe

- CHANGELOG.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/ExtendedAssetClass.hs
This adds two constants (for Haskell and Plutarch) representing the ADA asset class, as well as a predicate for verifying whether an arbitrary `ExtendedAssetClass` is the ADA one. This also 'burns in' the decision that the ADA class has a fixed, rather than arbitrary, token name, as per @t1lde's suggestion.
> More ExtendedAssetClass helpers

- CHANGELOG.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/Optics.hs
Amidst my work on `liqwid-onchain` to use `ExtendedAssetClass`, I found myself needing setter capability. However, `HasLabelledGetters` isn't powerful enough to describe that we have _lenses_ on a particular set of fields, only getters.
This PR provides the ability to 'collectively constrain' any number of fields to any optic of our choice, using a type family `HasLabelled`. Furthermore, we provide a backwards-compatible version of `HasLabelledGetters` based on this new design. This has been marked as deprecated for now, but at least it won't break anything.
> HasLabelled

- CHANGELOG.md
- src/Plutarch/Extra/Optics.hs
This provides `guarantee` and `guarantees`, which are variants of `preview` and `previews` which allow giving a default, similar to `fromMaybe`.
> guarantee and guarantees

- CHANGELOG.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/ExtendedAssetClass.hs
This adds two useful `ExtendedAssetClass` functions. Both were originally defined for Plutarch: these are their Haskell equivalents.
> eqClasses, unsafeToAssetClass

- CHANGELOG.md
- liqwid-plutarch-extra.cabal
- src/Plutarch/Extra/FixedDecimal.hs
Currently, `FixedDecimal` only encodes its numerator, as an `Integer`, when performing `Data` serialization. This is a problem: it is very easy to serialize a `FixedDecimal 9`, then deserialize a `FixedDecimal 2`, which can cause significant problems.
This PR repairs this problem by also serializing the `exp` tag as an `Integer`. `FromData` now checks this tag for consistency. `UnsafeFromData` still ignores it as previous, as (given that it's marked unsafe), we can assume that the user wishes to trade correctness checks for performance.
The `PConstantDecl` and `PUnsafeLiftDecl` instances in the `FixedDecimal` module have been updated appropriately to defer to `Data` encodings, as well as carry extra constraints.
> Fix Data representation for FixedDecimal
